### ISSUE TITLE
Running with NAO

### ISSUE THREAD

**Issue by stannoTUKE** [ElliotGestrin/NAOChat#3] opened 2023-06-29 13:16 UTC
Hello Elliot, 

I really thank you for your work. I tried to run your code with NAO. But it does not work for me.
![image](https://github.com/ElliotGestrin/NAOChat/assets/29484234/e9844ee8-1734-4fe9-a264-70dcad587626)

Could you help me to find the problem? I installed everything on my laptop.. nothing in NAO.. is it OK? I only connected NAO by IP adress. What's wrong? On desktop, it works (linux on Win11) on terminal, but not with mic (no device error)

Many thanks

**Comment by ElliotGestrin** [comment] 2023-06-29 13:41
Hi! Thanks for trying out the repo. The issue is the version of PyNaoQI you're using. I'd accidentally linked the 32-bit version instead of the 64-bit version. I've pushed a fix to the repo now.

Please try downloading the 64-bit version from [here](https://community-static.aldebaran.com/resources/2.1.4.13/sdk-python/pynaoqi-python2.7-2.1.4.13-linux64.tar.gz): https://community-static.aldebaran.com/resources/2.1.4.13/sdk-python/pynaoqi-python2.7-2.1.4.13-linux64.tar.gz. 

Then untar the 64-bit version and replace your current 32-bit "pynaoqi" folder with the new 64-bit version, yet again changing the name to "pynaoqi". If you prefer, the correct terminal commands are now also in the Readme.
ith the name changed to "pynaoqi"

Please let me know how the project works for you! I'd be excited to see it in action :smile:

**Comment by stannoTUKE** [comment] 2023-06-30 09:47
Hi Elliot, 

unfortunately, still the same problem... No module named naoqi.. any suggestion?

**Comment by ElliotGestrin** [comment] 2023-06-30 10:19
My bad yet again! I tried pushing a quick-fix while on the road yesterday, but clearly it was too quick and too little fix.

I pushed a new version just now that should hopefully fix your issue, as well as add the option to have local untracked configs. Please download it and try it!

For completeness sake I'll also mention that the issue was that the file "py2_nao_source" having been renamed by me, but I'd missed a reference to the old name, "python2_source". 

In regards to signing in I believe that the repo that's used for talking, "nao-demo", shouldn't require any login! However, I'll double check with the creator of that repo.

**Comment by stannoTUKE** [comment] 2023-06-30 13:29
Elliot, 

thank you so much.. this version work! I had some problems with audio settings, but I hope, It is fixed. After one dialogue exchange, NAO stopped talking, but I dont know why..

**Comment by stannoTUKE** [comment] 2023-06-30 13:48
Elliot, now it works! Thank you for your work and help! How can I change the language of the input? Which speech recognition the system use? Thank you

**Comment by ElliotGestrin** [comment] 2023-06-30 19:59
Glad to hear it works!

The default speech recognition is google's speech recognition API. However, setting the "use_whisper" config parameter to True will use OpenAI:s Whisper API instead. In my testing google seemed to give more accurate transcriptions, though Whisper does punctuation, capitalization and the like far better. It's using the [SpeechRecognition](https://pypi.org/project/SpeechRecognition/) package, so there are quite a few more versions that could be added as well. Feel free to make a PR if you'd like another one.

The language for them is controlled with the "language" config parameter, which should take the [ISO 639-1 code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for your language of choice, for example "en", "se" or "sk". 

If you make a project with the repo, please share it :smile:

**Comment by stannoTUKE** [comment] 2023-07-03 18:35
Hello,

thank you for your answers and suggestions. I will continue in my work
later this week.


Best regards
Stanislav Ondáš

doc. Ing. Stanislav Ondáš, PhD.

KEMT FEI TU Košice
Laboratory of speech and mobile technologies
Department of electronics and multimedia telecommunications
Faculty of Electrical Engineering and Informatics
Technical University of Košice
Slovak Republic
https://nlp.kemt.fei.tuke.sk/audiometry
https://nlp.kemt.fei.tuke.sk/dialog-research


pi 30. 6. 2023 o 22:00 Elliot Gestrin ***@***.***> napísal(a):

**Comment by ElliotGestrin** [comment] 2023-07-05 08:01
Good luck with your work! Since all the current issues appear to be solved I'll close this issue, but feel free to open another one or reach out to me if you have further problems or ideas.

**Closed by ElliotGestrin** 2023-07-05 08:01 UTC
Labels: bug

**Comment by stannoTUKE** [comment] 2023-07-05 09:33
Thank you very much.

Best regards

Stanislav Ondáš

doc. Ing. Stanislav Ondáš, PhD.

KEMT FEI TU Košice
Laboratory of speech and mobile technologies
Department of electronics and multimedia telecommunications
Faculty of Electrical Engineering and Informatics
Technical University of Košice
Slovak Republic
https://nlp.kemt.fei.tuke.sk/audiometry
https://nlp.kemt.fei.tuke.sk/dialog-research


st 5. 7. 2023 o 10:02 Elliot Gestrin ***@***.***> napísal(a):
